apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: mongo-sm
    labels:
      release: prometheus
spec:
  endpoints:
    - interval: 10s
      port: mongo
  selector:
    matchLabels:
      app: mongodb
    